version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootagos
      - DB_NAME=panaderia_stock

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    build:
      context: ./db
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: rootagos
      MYSQL_DATABASE: panaderia_stock
      # MYSQL_USER: root  # No es necesario ya que es el root por defecto
      # MYSQL_PASSWORD: rootagos  # No es necesario ya que es el root por defecto
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
