name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Build and run
          run: docker-compose up -d

    unit-test:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.17'

        - name: Run Unit Tests
          working-directory: backend
          run: go test -v ./...

    build-backend:
        needs: unit-test
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push Backend Image
          uses: docker/build-push-action@v2
          with:
             context: ./backend
             push: true
             tags: agostinamorellato/panaderia-stock-backend:latest

    build-frontend:

        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push Frontend Image
          uses: docker/build-push-action@v2
          with:
             context: ./frontend
             push: true
             tags: agostinamorellato/panaderia-stock-frontend:latest

    build-db:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push DB Image
          uses: docker/build-push-action@v2
          with:
             context: ./db
             push: true
             tags: agostinamorellato/panaderia-stock-db:latest

    integration-test:
        needs: build-db
        runs-on: ubuntu-latest
  
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
             node-version: 'latest'
  
        - name: Install Dependencies and CodeceptJS
          working-directory: frontend
          run: |
             npx playwright install
             npm install
             sudo apt-get install -y xvfb
  
        - name: Run Integration Tests with xvfb-run
         working-directory: frontend
         run: xvfb-run -a npx codeceptjs run --steps -d